language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
env:
  - DJANGO_VERSION=1.8.0
  - DJANGO_VERSION=1.8.6
# command to install dependencies
install: 
  #- pip install -r requirements.txt
  #- pip install -q Django==$DJANGO_VERSION
  #- python setup.py -q install

# command to run tests
script: 
  - git pull